services:
  login-server:
    volumes:
      - ./conf:/app/conf:ro
      - ./solutionfiles/secrets:/app/solutionfiles/secrets:ro

  char-server:
    volumes:
      - ./conf:/app/conf:ro
      - ./solutionfiles/secrets:/app/solutionfiles/secrets:ro

  map-server:
    volumes:
      - ./conf:/app/conf:ro
      - ./solutionfiles/secrets:/app/solutionfiles/secrets:ro
